### ISSUE TITLE
Production README

### ISSUE THREAD

**Issue by minuminukim** [minuminukim/memehub-express-project#1]
- [ ] Brief explanation of what the app is and does
- [ ] Link to live site
- [ ] Link to wiki docs
- [ ] Discussion of technologies used
- [ ] Discussion of two features that show off the team's technical abilities
- [ ] Discussion of both challenges faced and the way the team solved them
- [ ] Code snippets to highlight the best code

**Comment by w-duffy** [comment]
Completed
